components:
  parameters:
    WordId:
      name: wordId
      in: path
      required: true
      description: Word ID
      schema:
        type: integer
        format: int64

    SessionId:
      name: sessionId
      in: path
      required: true
      description: Game session ID
      schema:
        type: integer
        format: int64

    UserId:
      name: userId
      in: path
      required: true
      description: User ID
      schema:
        type: integer
        format: int64

    SearchQuery:
      name: q
      in: query
      required: true
      description: Search query (word to look up)
      schema:
        type: string
        minLength: 1
        maxLength: 255

    LanguageCode:
      name: language
      in: query
      required: false
      description: Language code to filter results (e.g., 'en', 'vi', 'zh')
      schema:
        type: string
        minLength: 2
        maxLength: 10

    LanguageId:
      name: languageId
      in: query
      required: true
      description: Language ID to filter results (required for dictionary search)
      schema:
        type: integer
        format: int32

    Limit:
      name: limit
      in: query
      required: false
      description: Maximum number of results to return
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

    Offset:
      name: offset
      in: query
      required: false
      description: Number of results to skip for pagination (alternative to page/pageSize)
      schema:
        type: integer
        minimum: 0
        default: 0

    Page:
      name: page
      in: query
      required: false
      description: Page number (1-based). Takes precedence over offset if both are provided
      schema:
        type: integer
        minimum: 1
        default: 1

    PageSize:
      name: pageSize
      in: query
      required: false
      description: Number of items per page. Takes precedence over limit if both are provided
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

    Email:
      name: email
      in: query
      required: true
      description: Email address to check
      schema:
        type: string
        format: email

    Username:
      name: username
      in: query
      required: true
      description: Username to check
      schema:
        type: string
        minLength: 3
        maxLength: 100
