#!/bin/bash

# Migration Script
# This script provides instructions for running database migrations (schema + data)

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo -e "${BLUE}🗄️  Database Migration Guide${NC}"
echo ""
echo -e "${YELLOW}This script provides instructions for running database migrations (schema + data).${NC}"
echo ""

# Check if PostgreSQL is accessible
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Prerequisites${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "• PostgreSQL database running"
echo "• Database credentials configured"
echo ""
echo "Start PostgreSQL (if not running):"
echo "   docker-compose -f deploy/compose/docker-compose.yml up -d postgres"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Option 1: Run Migrations Locally (Go)${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Step 1: Run Schema Migration"
echo ""
echo "   cd backend"
echo "   export DATABASE_URL='postgres://postgres:postgres@localhost:5500/english_coach?sslmode=disable'"
echo "   go run cmd/migration/schema/main.go"
echo ""
echo "   Or build and run:"
echo "   go build -o bin/migration-schema cmd/migration/schema/main.go"
echo "   ./bin/migration-schema"
echo ""
echo "Step 2: Run Data Migration"
echo ""
echo "   cd backend"
echo "   export DATABASE_URL='postgres://postgres:postgres@localhost:5500/english_coach?sslmode=disable'"
echo "   go run cmd/migration/data/main.go"
echo ""
echo "   Or run specific data migrations:"
echo "   go run cmd/migration/data/main.go --init              # Initial metadata only"
echo "   go run cmd/migration/data/main.go --word-en           # English words only"
echo "   go run cmd/migration/data/main.go --word-vi           # Vietnamese words only"
echo "   go run cmd/migration/data/main.go --word-zh           # Chinese words only"
echo "   go run cmd/migration/data/main.go --init --word-en    # Init + English words"
echo ""
echo "   Or build and run:"
echo "   go build -o bin/migration-data cmd/migration/data/main.go"
echo "   ./bin/migration-data"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Option 2: Run Migrations via Docker${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Step 1: Build the migration container"
echo "   docker build -f deploy/docker/backend/Dockerfile -t english-coach-migration backend/"
echo ""
echo "Step 2: Run Schema Migration"
echo "   docker run --rm \\"
echo "     --network english-coach-network \\"
echo "     -e DATABASE_URL='postgres://postgres:postgres@postgres:5432/english_coach?sslmode=disable' \\"
echo "     -v \"\$(pwd)/backend:/app\" \\"
echo "     -w /app \\"
echo "     english-coach-migration \\"
echo "     go run cmd/migration/schema/main.go"
echo ""
echo "Step 3: Run Data Migration"
echo "   docker run --rm \\"
echo "     --network english-coach-network \\"
echo "     -e DATABASE_URL='postgres://postgres:postgres@postgres:5432/english_coach?sslmode=disable' \\"
echo "     -v \"\$(pwd)/backend:/app\" \\"
echo "     -w /app \\"
echo "     english-coach-migration \\"
echo "     go run cmd/migration/data/main.go"
echo ""
echo "   Or run specific data migrations:"
echo "   docker run --rm \\"
echo "     --network english-coach-network \\"
echo "     -e DATABASE_URL='postgres://postgres:postgres@postgres:5432/english_coach?sslmode=disable' \\"
echo "     -v \"\$(pwd)/backend:/app\" \\"
echo "     -w /app \\"
echo "     english-coach-migration \\"
echo "     go run cmd/migration/data/main.go --init --word-en"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Option 3: Run Migrations Manually (psql)${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Schema Migration:"
echo "   psql -h localhost -U postgres -d english_coach -f backend/internal/infrastructure/db/migrations/schema/0001_init_schema.sql"
echo ""
echo "Data Migration:"
echo "   Note: Data migration must be run via Go program (not directly via psql)"
echo "   Use Option 1 or Option 2 above for data migration"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Migration Files${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Schema:"
echo "   backend/internal/infrastructure/db/migrations/schema/0001_init_schema.sql"
echo ""
echo "Data:"
echo "   backend/internal/infrastructure/db/migrations/data/0001_init_data.json"
echo "   backend/internal/infrastructure/db/migrations/data/0002_word_en.jsonl"
echo "   backend/internal/infrastructure/db/migrations/data/0003_word_vi.jsonl"
echo "   backend/internal/infrastructure/db/migrations/data/0004_word_zh.jsonl"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Verification${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "After running migrations, verify:"
echo ""
echo "1. Schema tables created:"
echo "   psql -h localhost -U postgres -d english_coach -c \"\\dt\""
echo ""
echo "2. Data seeded (check record counts):"
echo "   psql -h localhost -U postgres -d english_coach -c \"SELECT COUNT(*) FROM languages;\""
echo "   psql -h localhost -U postgres -d english_coach -c \"SELECT COUNT(*) FROM words;\""
echo ""
echo -e "${GREEN}For more details, see migration files in backend/internal/infrastructure/db/migrations/${NC}"
echo ""

